name: Deploy to EKS with ECR

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # AWS 인증
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    # ECR 로그인
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 이미지 빌드 & Push
    - name: Build and Push Docker images
      env:
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        echo "Building and pushing images with tag: $IMAGE_TAG"
        
        # Vote 이미지
        docker build -t vote ./vote
        docker tag vote:latest $ECR_REPOSITORY:vote-$IMAGE_TAG
        docker push $ECR_REPOSITORY:vote-$IMAGE_TAG

        # Result 이미지
        docker build -t result ./result
        docker tag result:latest $ECR_REPOSITORY:result-$IMAGE_TAG
        docker push $ECR_REPOSITORY:result-$IMAGE_TAG

        # Worker 이미지
        docker build -t worker ./worker
        docker tag worker:latest $ECR_REPOSITORY:worker-$IMAGE_TAG
        docker push $ECR_REPOSITORY:worker-$IMAGE_TAG

    # kubectl 설치 및 설정 (더 안정적인 방법)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: Set up kubeconfig for EKS
      run: |
        # kubeconfig 설정
        mkdir -p $HOME/.kube
        #echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        aws eks update-kubeconfig --name mx4pc-cluster --region ap-northeast-2    

    - name: Install and configure kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

      # # kubeconfig 설정
      # mkdir -p $HOME/.kube
      # #echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
      # chmod 600 $HOME/.kube/config

        # EKS 클러스터 연결 확인
        kubectl version --client
        kubectl cluster-info

    # EKS 클러스터 컨텍스트 업데이트 (선택사항 - 클러스터명이 있는 경우)
    - name: Update kubeconfig for EKS
      run: |
        # 만약 EKS 클러스터명을 알고 있다면 아래 명령어 사용
        # aws eks update-kubeconfig --region ap-northeast-2 --name ${{ secrets.EKS_CLUSTER_NAME }}
        
        # 현재 컨텍스트 확인
        kubectl config current-context
        kubectl get nodes

    # 매니페스트 이미지 업데이트
    - name: Update Kubernetes manifests
      env:
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.run_number }}  # github.sha 대신 run_number 사용 (일관성)
      run: |
        echo "Updating manifests with image tag: $IMAGE_TAG"
        
        # 파일 존재 확인
        ls -la custom-k8s-spec/
        
        # 이미지 업데이트
        sed -i "s|image:.*vote.*|image: $ECR_REPOSITORY:vote-$IMAGE_TAG|g" custom-k8s-spec/05-vote-deployment.yaml
        sed -i "s|image:.*result.*|image: $ECR_REPOSITORY:result-$IMAGE_TAG|g" custom-k8s-spec/07-result-deployment.yaml
        sed -i "s|image:.*worker.*|image: $ECR_REPOSITORY:worker-$IMAGE_TAG|g" custom-k8s-spec/09-worker-deployment.yaml

        # 변경사항 확인
        echo "Updated vote deployment:"
        grep "image:" custom-k8s-spec/05-vote-deployment.yaml
        echo "Updated result deployment:"
        grep "image:" custom-k8s-spec/07-result-deployment.yaml
        echo "Updated worker deployment:"
        grep "image:" custom-k8s-spec/09-worker-deployment.yaml

    # 배포
    - name: Deploy to EKS
      run: |
        echo "Applying Kubernetes manifests..."
        kubectl apply -f custom-k8s-spec/

        echo "Waiting for deployments to be ready..."
        kubectl rollout status deployment/vote --timeout=300s
        kubectl rollout status deployment/result --timeout=300s
        kubectl rollout status deployment/worker --timeout=300s

        echo "Deployment completed successfully!"
        kubectl get pods -l app=vote
        kubectl get pods -l app=result
        kubectl get pods -l app=worker