name: Deploy to EKS with ECR

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # AWS 인증
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    # ECR 로그인
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # 이미지 빌드 & Push
    - name: Build and Push Docker images
      run: |
        IMAGE_TAG=${{ github.run_number }}
        REGION=ap-northeast-2
        REPO_URI=${{ secrets.ECR_REPOSITORY }}

        docker build -t vote ./vote
        docker tag vote:latest $REPO_URI:vote-$IMAGE_TAG
        docker push $REPO_URI:vote-$IMAGE_TAG

        docker build -t result ./result
        docker tag result:latest $REPO_URI:result-$IMAGE_TAG
        docker push $REPO_URI:result-$IMAGE_TAG

        docker build -t worker ./worker
        docker tag worker:latest $REPO_URI:worker-$IMAGE_TAG
        docker push $REPO_URI:worker-$IMAGE_TAG

    # kubectl 설정
    - name: Setup kubectl, aws-iam-authenticator
      uses: kodermax/kubectl-aws-eks@v1
      with:
        args: version
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}


    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

    # 매니페스트 이미지 업데이트
    - name: Update Kubernetes manifests
      run: |
        IMAGE_TAG=${{ github.sha }}
        REGION=ap-northeast-2
        REPO_URI=${{ secrets.ECR_REPOSITORY }}

        sed -i "s|image:.*vote.*|image: $REPO_URI:vote-$IMAGE_TAG|g" custom-k8s-spec/05-vote-deployment.yaml
        sed -i "s|image:.*result.*|image: $REPO_URI:result-$IMAGE_TAG|g" custom-k8s-spec/07-result-deployment.yaml
        sed -i "s|image:.*worker.*|image: $REPO_URI:worker-$IMAGE_TAG|g" custom-k8s-spec/09-worker-deployment.yaml

    # 배포
    - name: Deploy to EKS
      run: |
        kubectl apply -f custom-k8s-spec/
        kubectl rollout status deployment/vote
        kubectl rollout status deployment/result
        kubectl rollout status deployment/worker
